### ISSUE TITLE
可以提供完整的代码吗？

### ISSUE THREAD

**Issue by helloworld-zj** [tonyckc/WT-PSE-code#1]
您好，最近读了您的作品很感兴趣，想尝试复现，发现train_process 文件没有给出，如果可以，麻烦您不吝上传，或发送到邮箱1002095799@qq.com，不胜感激！

**Comment by Taocunguo** [comment]
请问你找到了吗，可以发一份给我吗，1460535844@qq.com,非常感谢!

**Comment by tonyckc** [comment]
> 您好，最近读了您的作品很感兴趣，想尝试复现，发现train_process 文件没有给出，如果可以，麻烦您不吝上传，或发送到邮箱[1002095799@qq.com](mailto:1002095799@qq.com)，不胜感激！

please see the update

**Comment by tonyckc** [comment]
> 请问你找到了吗，可以发一份给我吗，[1460535844@qq.com](mailto:1460535844@qq.com),非常感谢!

please see the update

**Comment by tonyckc** [comment]
Dear all,

 Initial updating of code files has some problems due to the complicated file structure (some files are missed!). We now have provided corrected file list.

**Comment by tonyckc** [comment]
We have provided. So I close this issue.
